#ifndef TOKEN_H
#define TOKEN_H
#define SIZE 100

char tokenType[SIZE][SIZE];

enum tokID {
	BEGIN_TK, END_TK, LOOP_TK, VOID_TK, VAR_TK, RETURN_TK, IN_TK, OUT_TK, PROGRAM_TK, IFFY_TK, THEN_TK, LET_TK, DATA_TK,
	EQUALS_TK, EQUALS_EQUALS_TK, PLUS_TK, MINUS_TK, ASTERISK_TK, FORWARD_SLASH_TK, PERCENT_TK, LESS_THAN_TK, GREATER_THAN_TK,
	COLON_TK, PERIOD_TK, SEMI_COLON_TK, COMMA_TK, OPEN_PARENTHESIS_TK, CLOSE_PARENTHESIS_TK, OPEN_BRACE_TK,
	CLOSE_BRACE_TK, OPEN_BRACKET_TK, CLOSE_BRACKET_TK, ID_TK, INT_TK, EOF_TK
};

typedef struct {
	enum tokID tokenID;
	char tokenInstance[SIZE];
	int lineNumber;
} token;


#endif
